/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finaldbs;

/**
 *
 * @author Rio
 */
public class page2 extends javax.swing.JFrame {

    /**
     * Creates new form page2
     */
    String a, b, c, d, e, f, g,j;
    public page2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gk = new javax.swing.JCheckBox();
        anc = new javax.swing.JCheckBox();
        pvt = new javax.swing.JCheckBox();
        flk = new javax.swing.JCheckBox();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setText("ONLINE REGISTRATION FOR FUTSAL TEAM PU 2022");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Phase 2 : Choose Your Position");

        jLabel2.setText("Divion( Max choose 2 positions )");

        gk.setText("Goalkeeper");
        gk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gkActionPerformed(evt);
            }
        });

        anc.setText("Anchor");

        pvt.setText("Pivot");

        flk.setText("Flank");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anc)
                            .addComponent(flk)
                            .addComponent(gk)
                            .addComponent(pvt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Title)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(gk)
                .addGap(18, 18, 18)
                .addComponent(anc)
                .addGap(18, 18, 18)
                .addComponent(pvt)
                .addGap(18, 18, 18)
                .addComponent(flk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gkActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        page3 form3 = new page3();
        form3.a = a;
        form3.b = b;
        form3.c = c;
        form3.d = d;
        form3.e = e;
        form3.f = f;
        form3.j = j;
        if(gk.isSelected()&&anc.isSelected()){
            form3.i = gk.getText();
            form3.g = anc.getText();
        }
        if(gk.isSelected()&&flk.isSelected()){
            form3.i = gk.getText();
            form3.g = flk.getText();
        }
        if(gk.isSelected()&&pvt.isSelected()){
            form3.i = gk.getText();
            form3.g = pvt.getText();
        }
        if(anc.isSelected()&&gk.isSelected()){
            form3.i = anc.getText();
            form3.g = gk.getText();
        }
        if(anc.isSelected()&&pvt.isSelected()){
            form3.i = anc.getText();
            form3.g = pvt.getText();
        }
        if(anc.isSelected()&&flk.isSelected()){
            form3.i = anc.getText();
            form3.g = flk.getText();
        }
        if(pvt.isSelected()&&gk.isSelected()){
            form3.i = pvt.getText();
            form3.g = gk.getText();
        }
        if(pvt.isSelected()&&flk.isSelected()){
            form3.i = pvt.getText();
            form3.g = flk.getText();
        }
        if(pvt.isSelected()&&anc.isSelected()){
            form3.i = pvt.getText();
            form3.g = anc.getText();
        }
        if(flk.isSelected()&&gk.isSelected()){
            form3.i = flk.getText();
            form3.g = gk.getText();
        }
        if(flk.isSelected()&&anc.isSelected()){
            form3.i = flk.getText();
            form3.g = anc.getText();
        }
        if(flk.isSelected()&&pvt.isSelected()){
            form3.i = flk.getText();
            form3.g = pvt.getText();
        }
        form3.setVisible(true);
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JCheckBox anc;
    private javax.swing.JCheckBox flk;
    private javax.swing.JCheckBox gk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox pvt;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
